# Generated by Django 5.1.2 on 2024-10-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_about_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='portfolio',
        ),
    ]
