# Generated by Django 5.1.2 on 2024-10-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_remove_about_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFormSubmission',
            new_name='Contact',
        ),
    ]
